# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'KWC' do
  pod 'Stripe', '~> 11.2.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KWC

  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'CxxBridge',
    'DevSupport',
    'RCTNetwork','RCTWebSocket'
  ]
  pod 'AppCenter/Crashes', '~> 1.8.0'
  pod 'AppCenter/Analytics', '~> 1.8.0'
  pod 'AppCenterReactNativeShared', '~> 1.7.1'
  pod 'AppCenter/Push', '~> 1.8.0'
  pod 'AppCenter/Distribute'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  pod 'DoubleConversion', :podspec => "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "../node_modules/react-native/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "../node_modules/react-native/third-party-podspecs/Folly.podspec"


  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'
  platform :ios, '9.0'


  pod 'react-native-version-check', :path => '../node_modules/react-native-version-check'

  pod 'react-native-onesignal', :path => '../node_modules/react-native-onesignal'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
